"""Pure web-presence classification for the no-website lead finder.

Two tiers, both free of Apify calls:

  Tier A — ``classify_website`` reads the Google Maps ``website`` field and
  decides whether a business has no site, only a social/link-aggregator page, an
  http-only site, or a real https site. No network needed.

  Tier B — ``classify_live_site`` judges a real https site from the result of a
  local HTTP fetch (broken / parked / not-mobile / healthy). The fetch itself is
  I/O and lives in the orchestration script; the *decision* is pure and tested
  here.

A business is a lead unless its site is ``healthy`` (see ``is_lead_status``).
"""

import math
from urllib.parse import quote_plus

_AU_STATES = {"VIC", "NSW", "QLD", "SA", "WA", "TAS", "NT", "ACT"}


def _suburb_from_address(address):
    """Best-effort suburb from an Australian-format address string."""
    for part in address.split(","):
        tokens = part.strip().split()
        if any(t.upper() in _AU_STATES for t in tokens):
            kept = [t for t in tokens if t.upper() not in _AU_STATES and not t.isdigit()]
            if kept:
                return " ".join(kept)
    return ""


def extract_suburb(place):
    """Suburb from neighborhood/city, falling back to parsing the address."""
    for key in ("neighborhood", "city"):
        val = place.get(key)
        if val:
            return val.strip()
    address = place.get("address")
    if address:
        return _suburb_from_address(address)
    return ""


def dedupe_by_place_id(places):
    """Drop duplicate places sharing a placeId; places without an id are kept."""
    seen = set()
    result = []
    for place in places:
        pid = place.get("placeId")
        if pid:
            if pid in seen:
                continue
            seen.add(pid)
        result.append(place)
    return result


def parse_suburb_lines(text):
    """Parse a one-per-line file (suburbs or categories), ignoring blanks and # comments."""
    items = []
    for line in text.splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            items.append(line)
    return items


# Output CSV column order for the no-website lead finder.
LEAD_COLUMNS = [
    "business_name",
    "category",
    "web_status",
    "lead_tag",
    "rating",
    "reviews_count",
    "phone",
    "website",
    "suburb",
    "address",
    "tier",
    "tier_label",
    "heat",
    "google_maps_url",
    "google_search_url",
]

# Hosts that are a social profile or link aggregator, not an owned website.
# A business whose Google "website" points here still needs a real site.
_SOCIAL_HOSTS = {
    "facebook.com", "fb.com", "fb.me", "m.facebook.com",
    "instagram.com", "instagr.am",
    "linktr.ee", "linktree.com",
    "beacons.ai", "linkpop.com", "campsite.bio", "carrd.co",
    "twitter.com", "x.com",
    "tiktok.com",
    "wa.me",  # WhatsApp click-to-chat
}

# Substrings that mark a domain-parking / for-sale placeholder page.
_PARKED_SIGNATURES = (
    "domain is for sale",
    "this domain may be for sale",
    "buy this domain",
    "the domain you are looking for",
    "parked by",
    "domain parking",
    "sedoparking",
    "this webpage was generated by the domain owner",
    "is parked free",
)


def _host(url):
    """Lowercase host of a URL, without scheme/www/port; '' if unparseable."""
    from urllib.parse import urlparse
    if "://" not in url:
        url = "http://" + url
    host = (urlparse(url).hostname or "").lower()
    if host.startswith("www."):
        host = host[4:]
    return host


def classify_website(url):
    """Tier A: classify a Maps ``website`` value without fetching it.

    Returns one of: ``none``, ``social_only``, ``no_https``, ``live_site``.
    """
    if not url or not url.strip():
        return "none"
    url = url.strip()
    if _host(url) in _SOCIAL_HOSTS:
        return "social_only"
    if url.lower().startswith("http://"):
        return "no_https"
    return "live_site"


def classify_live_site(fetched_ok, status_code, html):
    """Tier B: judge a real https site from a local fetch result.

    Returns one of: ``broken``, ``parked``, ``not_mobile``, ``healthy``.
    """
    if not fetched_ok or status_code is None or status_code >= 400:
        return "broken"
    body = (html or "").lower()
    if any(sig in body for sig in _PARKED_SIGNATURES):
        return "parked"
    if 'name="viewport"' not in body and "name='viewport'" not in body:
        return "not_mobile"
    return "healthy"


def is_lead_status(status):
    """A business is a website-sales prospect unless its site is healthy."""
    return status != "healthy"


def is_real_listing(place, min_reviews):
    """True for a real, established business listing (not a locality centroid).

    Requires a title and a business category (localities/postcodes have neither)
    and enough reviews to prove it's a going concern. Phone is NOT required.
    """
    if place.get("permanentlyClosed"):
        return False
    if not place.get("title"):
        return False
    if not place.get("categoryName"):
        return False
    return (place.get("reviewsCount") or 0) >= min_reviews


# Plain-English label per web_status, naming the pitch angle for each lead.
_LEAD_TAGS = {
    "none": "Hot — no website",
    "social_only": "Hot — no website, strong social",
    "broken": "Redesign — site not loading",
    "not_mobile": "Redesign — not mobile-friendly",
}


def lead_tag(web_status):
    """A human-readable tag describing why a listing is a lead (and the pitch)."""
    return _LEAD_TAGS.get(web_status, "")


# --- ICP ranking (single source of truth, mirrored by web/src/lib/leads.ts) ---
# Tier encodes the ideal-customer-profile priority from CLAUDE.md:
#   1  social_only + phone  — best of the best (proven social spend + reachable)
#   2  social_only          — strong signal, no site fetch needed
#   3  none + phone         — clean gap, easy to reach
#   4  none                 — clean gap, reach via socials/maps
#   5  broken / not_mobile  — redesign buckets, lower confidence
_TIER_LABELS = {1: "Top tier", 2: "Social only", 3: "No website",
                4: "No website", 5: "Redesign"}
_TIER_BASE = {1: 78, 2: 62, 3: 58, 4: 44, 5: 30}


def lead_tier(web_status, has_phone):
    """ICP priority tier (1 = hottest) for a classified lead. Pure, no I/O."""
    if web_status == "social_only":
        return 1 if has_phone else 2
    if web_status == "none":
        return 3 if has_phone else 4
    return 5


def lead_tier_label(tier):
    """Short human label for a tier (matches the dashboard chips)."""
    return _TIER_LABELS.get(tier, "Redesign")


def lead_heat(tier, reviews_count, has_phone):
    """0–100 confidence/heat for the signal meter. Reviews are log-scaled so a
    3000-review business doesn't dwarf a 200-review one; a phone adds reach."""
    base = _TIER_BASE.get(tier, 30)
    traction = min(18.0, math.log10(max(1, reviews_count or 0)) * 5)
    reach = 4 if has_phone else 0
    return round(min(100.0, base + traction + reach))


def google_search_url(name):
    """A one-click Google search link for a business (opens its profile panel)."""
    if not name:
        return ""
    return "https://www.google.com/search?q=" + quote_plus(name)


def no_website_row(place, web_status):
    """Map a raw Google Maps place + its web_status to an output CSV row."""
    name = place.get("title") or ""
    phone = place.get("phone") or place.get("phoneUnformatted") or ""
    has_phone = bool(phone.strip())
    reviews = place.get("reviewsCount")
    tier = lead_tier(web_status, has_phone)
    return {
        "business_name": name,
        "category": place.get("categoryName") or "",
        "web_status": web_status,
        "lead_tag": lead_tag(web_status),
        "rating": place.get("totalScore"),
        "reviews_count": reviews,
        "phone": phone,
        "website": place.get("website") or "",
        "suburb": extract_suburb(place),
        "address": place.get("address") or "",
        "tier": tier,
        "tier_label": lead_tier_label(tier),
        "heat": lead_heat(tier, reviews, has_phone),
        "google_maps_url": place.get("url") or "",
        "google_search_url": google_search_url(name),
    }
